# general setting
batch_size: 16
input_height: 300
input_width: 400
backbone_type: 'MobileNetV2'  
sub_name: 'retinaface_mbv2'

# training dataset
dataset_path: './data/train_bin_new.tfrecord'
dataset_len: 12880  # number of training samples
using_bin: True
using_flip: True
using_distort: True

# testing dataset
testing_dataset_path: './data/widerface/val'

# network
out_channel: 64

# anchor setting
min_sizes: [[64,85], [112, 148], [194, 256]] # min_sizes:代表了三种尺度下两个 anchor 的大小
steps: [8, 16, 32]
match_thresh: 0.45
ignore_thresh: 0.3
variances: [0.1, 0.2]
clip: False

# training setting
epoch: 100
init_lr: !!float 1e-3
lr_decay_epoch: [50, 68]
lr_rate: 0.1
warmup_epoch: 2
min_lr: !!float 1e-4

weights_decay: !!float 5e-4
momentum: 0.9

pretrain: True

save_steps: 1000
